# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll.xci
# IP: The module: 'my_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll.xci
# IP: The module: 'my_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/my_pll/my_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
