# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.srcs/sources_1/ip/fifo_512x8/fifo_512x8.xci
# IP: The module: 'fifo_512x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.srcs/sources_1/ip/fifo_512x8/fifo_512x8.xci
# IP: The module: 'fifo_512x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/fifo_512x8/fifo_512x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
