# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/rom_col_axle/rom_col_axle.xci
# IP: The module: 'rom_col_axle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/rom_col_axle/rom_col_axle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_col_axle'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/rom_col_axle/rom_col_axle.xci
# IP: The module: 'rom_col_axle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/proj/my_project/my_project.srcs/sources_1/ip/rom_col_axle/rom_col_axle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_col_axle'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
