# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.srcs/sources_1/ip/rom_row_axle/rom_row_axle.xci
# IP: The module: 'rom_row_axle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/rom_row_axle/rom_row_axle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_row_axle'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.srcs/sources_1/ip/rom_row_axle/rom_row_axle.xci
# IP: The module: 'rom_row_axle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/my_fpga/fpga_project1_High_speed_ADDA_realTime_spectrum_analyzer_PL/code/prj/top_ad_da_fir_lcd.gen/sources_1/ip/rom_row_axle/rom_row_axle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_row_axle'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
